
using System.Reflection;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("TFLLib")]
[assembly: AssemblyDescriptionAttribute("Knoware 3000 Assembly.")]
[assembly: AssemblyCompanyAttribute("Knoware")]
[assembly: AssemblyProductAttribute("EA3000")]
[assembly: AssemblyCopyrightAttribute("Copyright (C) 2003-2005, Knoware")]
[assembly: AssemblyVersionAttribute("703.14.*")]

[assembly: System.CLSCompliant(false)]

